appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tgC3LaOXs+36lqoF6JdybhOvBCkx4B/p1rRqhXjD05v83wkksvs9cx0QAAo9/IkEuPMOhNSu4aEf9La+1aNqVd3yxr+ZlggvIXyooYvCuD+m8ADMndAP+mqqU0n8D8PD/36prBvMUYeKbp9Mqy4PQzUny5SfOSZviuoVAxjSTaYwhVi7nKUlvNsAW1d8BsBXJEHDr7X61zvOvyCM5w4cwWNmingFJxn2S5WRfrILHS2Xfyr8LE6Dfq95Wnhsdqx7vEL3JmJDccZ/7BFyb8gtngC8D/vJUK+LaB9176D2yIz3/boUZTy4Q0CvvXXFbjbycYSRRtvWYaguf0kc4ds3dXa1bQi5AgWP47WwWAUAdHnCYOvtqe026AWtnkgEJ6zf4j6d5PnZWyur1aV3v6gS/Rh3ZCwf8M0D80pfPtI69VCsca4YbdQc4Ym75N2FznFnH1wr0bDObCXHabJ2Wr5m4ZOMtSPKQhkN/iBXjDP1GiG1b77ELZjslK8ta5Hs50v4N7PkqpxkskhhlhIHj2fIFFvoeUASGKjRmw4C7BAohJ13pkd4eX+r1zGucYSpWjxODTEBiPqrMenuOjwdbnS6v/5ASBBIl8DRlsQ9JXRltFJnaa5YAZTRjkkNJ5GfxUP9+DqT/ADYLbME6BqnzDHR4qld7Lk1fV6ezHPn55iKnE8=}
conda_forge_output_validation: true
